services:
  py:
    container_name: py
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATADOG_TRACE_AGENT_HOSTNAME: otelcol
      DATADOG_TRACE_AGENT_PORT: 8126
      DATADOG_SERVICE_NAME: py
      DATADOG_ENV: local
      DATADOG_PATCH_MODULES: "requests:true"

      DD_AGENT_HOST: otelcol
      DD_DOGSTATSD_PORT: 8125
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    command: sleep infinity

  otelcol:
    container_name: otelcol
    image: otel/opentelemetry-collector-contrib:0.112.0
    volumes:
      - ./otelcol.yaml:/etc/otelcol-contrib/config.yaml

  lgtm:
    container_name: lgtm
    image: docker.io/grafana/otel-lgtm:0.7.6
    ports:
      - 3000:3000
    volumes:
      - grafana:/data/grafana
      - prometheus:/data/prometheus
      - loki:/loki
    environment:
      GF_PATHS_DATA: /data/grafana
      ENABLE_LOGS_OTELCOL: true
      ENABLE_LOGS_PROMETHEUS: true

volumes:
  grafana:
  prometheus:
  loki:
