version: '3'

tasks:
  up:
    cmds:
      - docker compose up -d {{.CLI_ARGS}}
  down:
    cmds:
      - docker compose down {{.CLI_ARGS}}
  restart:
    cmds:
      - docker compose restart {{.CLI_ARGS}}
  build:
    cmds:
      - docker compose build {{.CLI_ARGS}}
  ps:
    cmds:
      - docker compose ps {{.CLI_ARGS}}
  logs:
    cmds:
      - docker compose logs {{.CLI_ARGS}}
  logsf:
    cmds:
      - docker compose logs -f {{.CLI_ARGS}}
  in:
    cmds:
      - docker compose exec {{.CLI_ARGS}} /bin/bash
  clean:
    cmds:
      - docker compose down -v

  main:
    cmds:
      - docker compose exec py python app/main.py
  grafana:
    cmds:
      - open http://localhost:3000
